apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-proxy-ping-fixed
  namespace: redis
  labels:
    app: redis-cluster-proxy-ping-fixed
    version: 1.0.0
spec:
  type: ClusterIP
  selector:
    app: redis-cluster-proxy-ping-fixed
  ports:
    - name: redis
      port: 7777
      protocol: TCP
      targetPort: 7777
  sessionAffinity: None
  internalTrafficPolicy: Cluster
